const fs = require("fs");
const PDFDocument = require("pdfkit");

// JSON data
const jsonData = [
  {
    id: "06ae67a9-c084-4816-935c-0d76276132cb",
    title: "Alnwick Road Detached",
    code: "DEPARTMENT-21",
    address: "Alnwick Road Hougang / Punggol / Sengkang (D19)",
    distance: "18 mins (1.5 km) from CR10 Tavistock MRT",
    amount: "8280000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-alnwick-road-detached-24321965",
    about:
      '"About this propertyMust sell! majestic detach hse, 4-mins walk to chomp-chomp & myvillage*** LOCATED IN THE HEART OF SERANGOON GARDEN ****** 4 MINS WALK TO CHOMP CHOMP,  myVILLAGE MALL****** 1KM TO ROSYTH SCHOOL***2.5 Storey Bungalow for Sale!Designed and Built (2011) by Renowned Architect: AAMERTimeless Design, Spectacular, Majestic HouseMove in ready- Land: 4,620sqft- Built up: 5,500sqft approx- Tenure: 999yrs leasehold wef 1954- Main Gate/Door Facing: North-West- Regular Land- Wide Frontage (13.11m wide)- 2.5 Storey- 6 Bedrooms- park 2-3 cars in porch- In-ground Lap Pool- Movie Room- Quality fixtures and appliancesCall Exclusive agent (SRI) JACKIE CHEW 9***** for viewing appointment now.Schools within 1km:CHIJ Our Lady of Good CounselRosyth SchoolZhonghua Primary School Show more"',
    bed: 6,
    bath: 6,
    sqft: "4620",
    psf: "S$ 1,792",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "0d075ddb-3c3f-4a0d-b64c-c7b084dc96e4",
    title: "Reflections at Keppel Bay",
    code: "DEPARTMENT-37",
    address: "25 Keppel Bay View Harbourfront / Telok Blangah (D04)",
    distance: "14 mins (1.2 km) from CC28 Telok Blangah MRT",
    amount: "25500000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-reflections-at-keppel-bay-23173509",
    about:
      '"About this property: Best penthouse, Awesome Sea, Sentosa and Lush Greenery views. Reflections by Keppel Bay World famous architect Daniel Libeskind built this Feng Shui friendly residential development shaped like Dragon Teeth Gate 龙牙门 for prime developer Keppel Land. Its exterior structural column of this condominium is an art piece. Penthouse (renovated, excellent sea, marina and Sentosa view): - 8,277 sq ft - 4 bedrooms ensuite + 1 big study / home office / guest room with adjoining bathroom - Imported curtain rails from Holland - All exterior aluminium window frame and cladding were professionally polished - Marble skirting and parquet skirting, one n only kind in Reflections, are installed around the pillars indoors - Parquet flooring - white washed American oat parquet - Top end washing machine, dryer, dishwasher, oven, microwave oven, hob and hood from luxurious Swiss brand, V-Zug - Taps/Faucets in kitchen and all bathrooms from Philippe Starck by Hans Grohe Axor (high end), not Grohe or Hans Grohe - All washbasins n wall mounted toilets and BD from Duravit - Concealed wiring n cabling for broadband service (WIFI) via ceiling routers - Sonos sound system with ceiling speakers - All ironmongery are from Häfele, a German brand - Furniture from Roche Bobois, Eileen Grey - Original Lem bar stools - All doors are lacquered with high gloss lacquer imported from Italy; customised door flaps are installed to shut out noise, humidity and haze - All glass windows and doors are double glazed throughout the penthouse (very quiet) - The living room decorative ceiling is installed with specially sourced Italian steel plates with design of waves to reflect the waters outdoor as in Reflections - Travertine bar with induction hob; 2 wine chillers and liquor bar hidden behind wood lattice panel Call Soo Cheng for an exclusive viewing."',
    bed: 5,
    bath: 6,
    sqft: "8277",
    psf: "S$ 3,081",
    createdAt: "2024-06-21T05:48:58.000Z",
    updatedAt: "2024-06-21T05:48:58.000Z",
    deletedAt: null,
  },
  {
    id: "1b6f9c8e-d558-4f44-a461-90aa953baf9a",
    title: "Teow hock",
    code: "DEPARTMENT-22",
    address: "Teow hock Hougang / Punggol / Sengkang (D19)",
    distance: "13 mins (1.1 km) from NE13 Kovan MRT",
    amount: "4100000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-teow-hock-25080370",
    about:
      '"About this propertyHuge land freehold landedBrand new listing Inter terrace with huge land for sale5 bedrooms3 toilets Suitable for rebuilt or AnASerious seller To viewAlll you have to do, is Ask! 8***** I’ll see you Show more"',
    bed: 5,
    bath: 3,
    sqft: "2320",
    psf: "S$ 1,767",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "1e2353ae-2a63-4381-9e79-d37c0b13443a",
    title: "Whitley Villas",
    code: "DEPARTMENT-2",
    address: "115F Whitley Road Newton / Novena (D11)",
    distance: "5 mins (420 m) from TE10 Mount Pleasant MRT",
    amount: "4080000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-whitley-villas-24785505",
    about:
      "\"About this propertyRare Freehold Corner Semi D in D11New exclusive listing.If you are looking for a freehold semi d around $4.5M, this might be the perfect home for you.Pure selling, NO Extension required!Cobroke welcome, 50/50!3 Storey + basement Corner Semi D in D11Built Up: 3025 sqftTenure: FreeholdMCST Fees: $1000/QuarterFurthest unit from main road offering lots of space, quiet and privacyBasement:- Private parking for 2 cars- Granny room en suite- Helper's room with own toilet- Home shelter- Storage- Backyard Laundry areaLevel 1:- direct access to swimming pool- Living room- Dining area- Wet and dry kitchen- Good size outside patio area, big enough for outdoor family dining or   BBQ area- Good sized back yard- ToiletLevel 2- 1 en suite bedroom- 2 common bedrooms + common bathroomLevel 3- Huge master bedroom en suite with walk in wardrobe------------------------------------------------------------------------------------------------------Transport:- Mount Pleasant Mrt (TE 10): 0.35km- Novena Mrt (NS 20): 0.97kmPrimary schools:- Anglo-Chinese School: 0.87km- CHIJ TPY: 0.92km- Singapore Chinese Girl's School: 1.27km- St Joseph's Institution Junior: 1.35km- Marymount Convent School: 1.55kmChildcare:- Chiltern House: 0.77km- Pat's Schoolhouse: 0.79km- Mindchamps: 0.83km- Kiddiwinkie Schoolhouse: 0.80km- The Little Skool-house International: 0.83kmMalls & Supermarket:- Balestier Hill Shopping Centre: 0.5km- Square 2: 0.9km- Zhongshan Mall: 1km- Novena Square: 1km- Velocity@ novena Square: 1kmConnect with Alvin today to view this fantastic property right away. Show more\"",
    bed: 5,
    bath: 6,
    sqft: "3025",
    psf: null,
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "1f40822d-c264-4dd7-8c45-bdc0da213295",
    title: "The Peak @ Cairnhill I",
    code: "DEPARTMENT-18",
    address: "51 Cairnhill Circle Orchard / River Valley (D09)",
    distance: "14 mins (1.2 km) from NS23 Somerset MRT",
    amount: "1250000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-the-peak-cairnhill-i-24767827",
    about:
      "\"About this propertyS.U.P.E.R C.H.E.A.P, gorgeous 1-bedder in town for sale!A gorgeous freehold gem at Cairnhill for sale!Well-maintained, nicely renovated, and priced to sell.Sale with tenancy until 21 Mar 2024.High rental yield! Perfect for own-stay or investment.Details- 1-bedder, 527 sqft, 49sqm- High-floor, with good views- Freehold- Obtained TOP in 2015 (only 8 years old!)MRTs- Newton MRT (8 minute's walk)- Orchard MRT Station (15 minutes' walk)Food Centre- Newton Circus Food Centre (7 minutes' walk)Primary Schools within 1km- ACS Junior- St. Margaret's SchoolMalls within 1km- Far East Plaza- The Paragon- Knightsbridge- Lucky Plaza- Scotts Square- Tang Plaza- Midpoint Orchard- The Centrepoint- Ngee Ann City- 313 @ Somerset- Wisma Atria- Shaw House- Cathay Cineleisureand more!Contact Felix Ethan at 9***** to schedule an exclusive viewing soon!Service you can trust,Felix Ethan TanJNA Real Estate Show more\"",
    bed: 1,
    bath: 1,
    sqft: "527",
    psf: "S$ 2,372",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "20eaa408-92bc-471d-a62d-e39df90e730a",
    title: "Affinity At Serangoon",
    code: "DEPARTMENT-10",
    address: "24 Serangoon North Avenue 1 Hougang / Punggol / Sengkang (D19)",
    distance: "11 mins (950 m) from CR9 Serangoon North MRT",
    amount: "2000000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-affinity-at-serangoon-24866443",
    about:
      '"About this propertyBrand New 3 Bedder TOP Unit at SerangoonExclusive 3 Bedder For Sale!-1152sft-3 bedder with utility and yard-Just TOP-Brand New-Bright and Breezy-NS Facing-No Afternoon Sun-Main Door Face South-Functional Layout-Full condo facilities-Shuttle Bus to MRT-Sheltered walkway to Bus Stop-Few stops to Serangoon MRT-Easily accessible to major expressway CTE / PIE / SLE / TPE-Mins to Serangoon Garden-Keys on hand, Viewing anytimePrimary Schools within 1km-Zhonghua Primary School-Rosyth SchoolCall Dylan Su @          9*****         for an exclusive viewing today! Show more"',
    bed: 3,
    bath: 2,
    sqft: "1152",
    psf: "S$ 1,736",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "22193f3b-e0a5-4247-bb19-52dd78e93214",
    title:
      "Spacious Good Class Bungalow Located Within a Nice & Quiet Landed Estate",
    code: "DEPARTMENT-20",
    address: "Tanglin / Holland / Bukit Timah (D10)",
    distance: "12 mins (960 m) from DT6 King Albert Park MRT",
    amount: "30000000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-spacious-good-class-bungalow-located-within-a-nice-quiet-landed-estate-24936953",
    about:
      "\"About this propertyEmbrace Timeless Grandeur: Vintage Charm & Abundant SpaceWelcome to a world of opulence and exclusivity! Home of the Elites Pte Ltd invites you to explore a breathtaking 2-storey Good Class Bungalow in the heart of Bukit Timah. Nestled in a prime location, this exceptional property boasts a vast land area of 16,500 sqft (approx) and a spacious built-up space of 9,000 sqft (approx).Property Highlights: 7 Ensuite Bedrooms TV Room, Helper's Room, and Family Area Inviting Inground PoolPrime Location:Discover the allure of living in one of Singapore's most prestigious neighborhoods. Good Class Bungalows in Bukit Timah are a rare find, and this exclusive property offers a unique opportunity to indulge in luxury living.Limited Availability: With only 2400 Good Class Bungalows in Singapore, owning one in the coveted Bukit Timah vicinity is a privilege reserved for the discerning few. Act fast – this property is priced to sell!Proximity to Amenities: Enjoy the convenience of reputable schools, an educational hub, shopping malls, supermarkets, F&B outlets, and more, all within reach. The MRT is also within walking distance, ensuring seamless connectivity.Ready to experience the epitome of luxury living? Contact Home of the Elites Pte Ltd now to schedule an exclusive viewing! Your dream Good Class Bungalow awaits.Call Now to Secure Your Slice of Bukit Timah Luxury!Disclaimer: Images for Illustration Purposes OnlyPlease note that the images included are for illustrative purposes, showcasing the potential of the property. Actual features, finishes, and conditions may vary. We recommend scheduling a viewing to experience the property firsthand and make an informed decision. Your understanding is appreciated.\"",
    bed: 7,
    bath: 8,
    sqft: "16500",
    psf: "S$ 1,818",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "231b09dd-5899-482b-bc44-189f9786ffd1",
    title: "Suites @ Katong",
    code: "DEPARTMENT-13",
    address: "263 Tanjong Katong Road East Coast / Marine Parade (D15)",
    distance: "12 mins (1 km) from TE25 Tanjong Katong MRT",
    amount: "699999",
    link: "https://www.propertyguru.com.sg/listing/for-sale-suites-katong-25018949",
    about:
      '"About this property1km within reputable primary schoolFreehold property with affordable quantum. Mixed-use development for commercial and residential purposesWith a view of Tanjong Katong RoadAvailable for sale with existing tenancy until May 2025Currently rented out for $2,500(MCST) fees price to $527 per quarterEquipped with mechanical parking facilitiesSchools within 1km:Haig Girls\' SchoolKong Hwa SchoolTanjong Katong Primary SchoolThere is a number of public transportation close to Suites @ Katong that residents can make use of. The closest MRT station to Suites @ Katong is Dakota MRT Station. The closest bus stops are located at Tanjong Katong Girls’ School, Tanjong Katong Secondary School, Dunman View, Maranatha Hall, One Amber and Varsailles Condominium. For those with vehicles, the shopping district located at Orchard Road can be easily accessed via Nicoll Highway and the Central Expressway in 20 to 25 minutes.Suites @ Katong is a beautiful condominium that has many charms to it. There are various facilities that residents can enjoy while living in Suites @ Katong. Residents of Suites @ Katong would not have to travel far to get their basic necessities as everything is close within their reach. Residents can enjoy the barbeque area, gymnasium room, swimming pool and jacuzzi. The condominium comes equipped with covered car parks that protect residents from the harsh weather of Singapore.#freehold #investment #konghwa #haiggirls Show more"',
    bed: 1,
    bath: 1,
    sqft: "388",
    psf: "S$ 1,804",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "2bd0e922-4a09-46b0-b1a4-f2d24faee497",
    title: "Penrose",
    code: "DEPARTMENT-36",
    address: "20 Sims Drive Eunos / Geylang / Paya Lebar (D14)",
    distance: "7 mins (590 m) from EW9 Aljunied MRT",
    amount: "3190000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-penrose-25042103",
    about:
      '"About this property: Genuine Brand New Listing! Perfect for Familes! Full Facilities! [Real!! Legit!! Genuine!!] - 4 Beds 3 Baths 1 Wc - Ideal for Families - Full Condo Facilities - Facing AWAY from the expressway - No West Sun - Squarish and Efficient Layout - Able to house Queen size bed in All bedrooms - TOP Soon MRT Stations: Aljunied MRT: 5 Mins\' Walk Paya Lebar MRT: 1 Station Away Schools within 1KM: Geylang Methodist School Canossa Catholic Primary School Schools within 1KM to 2KM: Kong Hwa School Bendemeer Primary School Cedar Primary school St. Andrew Junior School International School: James Cook University Singapore Nexus International School Shopping Centre: Paya Lebar Quarter Paya Lebar Square SingPost Centre KINEX Kallang Wave Mall Food Centres: Sims Vista Market & Food Centre Haig Road Market & Cooked Food Centre Old Airport Food Centre Contact Wayne @ 9***** to find out more TODAY!"',
    bed: 4,
    bath: 3,
    sqft: "1389",
    psf: "S$ 2,297",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "2c8aeab6-d36c-490b-b0b5-c11c6b94f4cb",
    title:
      "EXCLUSIVE! D10, SUB-DIVISIBLE PLOT. WIDE FRONTAGE. 1KM HPPS.TRANQUIL LOCALE.",
    code: "DEPARTMENT-1",
    address: "Mt Sinai/Grove/Holland Tanglin / Holland / Bukit Timah (D10)",
    distance: "30 mins (2.5 km) from EW22 Dover MRT",
    amount: "16800000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-freehold-landed-living-with-mrt-at-doorstep-foreigner-and-pr-can-buy-25098363",
    about:
      '"About this propertyPark Facing. Corner Bungalow. Rare Gem.- 1km to Henry Park Primary School.- Mins Walk to MRT.- For Greenery Lover.* All land and built up areas are approximate measurements and subject to final survey and shall not form part of any offer or contract nor constitute any warranty by the salesperson and shall not be regarded as statements or representations of fact*For more information, please call          8*****        .SOLE AGENTJames Ng          8*****        Sub-divisible bungalow Plots within District 9, 10, 11, 21, 20, 23 & 15.  | Semi-detached | Detached | Good Class Bungalows near the Prestigious Schools. | Nanyang Primary School NYPS | Singapore Chinese Girls School SCGS | Raffles Girls School RGPS | Anglo Chinese School ACS | Henry Park Primary School | Methodists Girls School MGS | Tan Kah Kee MRT | Sixth ave MRT | Guthrie House | Cluny court | Botanic Garden | Andrew Road | Arnap | Barker Road | Ash Grove | Astrid Hill | Belmont | Berrima road | Cable Road | Cluny Hill | Chatsworth | Nassim | Nathan |  Trevose cres | Camden Park | Linden | Narrooma Road | Dalkeift Road | Bin Tong Park | Rebecca road | Bishopgate | Rochalie Drive | Jervois | Chee Hoon | University | Namly | Watten | Hillcrest | Chancery | King\'s Road | Duchess | Cornwall | Oei Tiong Ham | Ewart Park | Sian Tuan | Hua Guan | Binjai | Swettenham | Pierce Hill | Kingsmead | Vanda | Oriole | Stevens | Robin | Coronation | Gentle | Rebecca | Victoria | Bin Tong Park | Dalvey Estate | One Tree Hill | Mount Echo Park | Show more"',
    bed: 5,
    bath: 5,
    sqft: "7100",
    psf: "S$ 2,366",
    createdAt: "2024-06-21T05:48:55.000Z",
    updatedAt: "2024-06-21T05:48:55.000Z",
    deletedAt: null,
  },
  {
    id: "2f435e14-899d-407d-a55e-75040305a5d5",
    title: "The Crest",
    code: "DEPARTMENT-28",
    address: "101 Prince Charles Crescent Alexandra / Commonwealth (D03)",
    distance: "10 mins (790 m) from EW18 Redhill MRT",
    amount: "3900000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-the-crest-24668423?pixelUrl=https%3A%2F%2Fe-11135.adzerk.net%2Fe.gif%3Fe%3DeyJ2IjoiMS4xMSIsImF2IjoyMjAyMDUxLCJhdCI6MTYzLCJidCI6MCwiY20iOjIwNjkyNDY2MiwiY2giOjU5NTM0LCJjayI6e30sImNyIjozNDY5NTA5OTgsImRpIjoiNjhhZDQ0ZjRhMGY3NGE1MmEyMWFmMzZkMTgxM2VjMTUiLCJkaiI6MCwiaWkiOiJkNmJlOWUwNDc2ZjA0MmY1YjIyNTcxYjc2YzkzM2RhYSIsImRtIjozLCJmYyI6NTIyMjI3Mzc1LCJmbCI6NTEwOTc3Mzc1LCJpcCI6IjE2Mi4xNTguMTYyLjYyIiwia3ciOiJsaXN0aW5nLXNhbGUtcHJvcC1uLHByaWNlIiwibWsiOiJsaXN0aW5nLXNhbGUtcHJvcC1uLHByaWNlIiwibnciOjExMTM1LCJwYyI6MTQwMCwib3AiOjE0MDAsImVjIjoxNDAwLCJnbSI6MCwiZXAiOm51bGwsInByIjoyMzU3MTQsInJ0IjoyLCJycyI6NTAwLCJzYSI6IjQ3Iiwic2IiOiJpLTA3ZDZkMzE2YTUxOTQzMDY3Iiwic3AiOjIzOTk3Nywic3QiOjExOTg3MTgsInVrIjoiMTMwMGNiZGUtYTdiOS00YzgxLWIxMjQtMTdmY2I4NWJhYWZlIiwidHMiOjE3MTI4MzAwNDg4MDYsImJmIjp0cnVlLCJwbiI6IjEiLCJnYyI6dHJ1ZSwiZ0MiOnRydWUsImdzIjoibm9uZSIsInR6IjoiVVRDIiwiZXQiOjIwNX0%26s%3DIvUaxWQpduGWy8IuyD9NgmDCapM",
    about:
      '"About this property: Luxurious Designer 4 Br Penthouse High Ceiling Walk Mrt Mall Orchard. The Crest Luxurious Designer 4 Br Penthouse Double Ceiling Height At Prince Charles Crescent RCR City Fringe with Huge Facilities Landscape and Mins Walk to MRT and Mall. DON’T MISS THIS: 1. Private Lift (direct to inside house) 2. Ample parking lots 3. TOP ID Interior which costs $600K 4. High Ceiling House 5 metre Penthouse 5. All Lightings are imported from Italy 6. Loft with curved staircase 7. Balcony - ideal for cosy gatherings 8. Miele coffeemaker, Electrolux stove / oven / microwave, Bosch dishwasher 9. Master Bedroom and Junior Master with En-suite Bathroom 10. Helper’s Room & WC 11. Ample storage cabinets"',
    bed: 4,
    bath: 4,
    sqft: "1873",
    psf: "S$ 2,082",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "2fa508d7-1eed-47d1-9fe7-11782a21f944",
    title: "Surin Villas",
    code: "DEPARTMENT-27",
    address: "Upper Serangoon Road Hougang / Punggol / Sengkang (D19)",
    distance: "12 mins (1000 m) from NE13 Kovan MRT",
    amount: "3780000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-surin-villas-24985757",
    about:
      '"About this property: Nicely renovated and convenient location. New list by PropNex Eminence Landed Team. - Tenure: Freehold - Build up: 5231sqft - Rooms: 4 + 1 - Ensuite: 4 - Bath: 6. Wet and dry kitchen. Swimming pool. Car porch for 2 cars. Extension required. Looking for a home that is bright and well ventilated? Look no further. Move-in condition. Within 1km to Paya Lebar Methodist Girls School."',
    bed: 4,
    bath: 6,
    sqft: "5231",
    psf: null,
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "3940c26f-b649-4945-b616-a0206d416445",
    title: "Balmoral 8",
    code: "DEPARTMENT-30",
    address: "8 Balmoral Road Tanglin / Holland / Bukit Timah (D10)",
    distance: "17 mins (1.4 km) from DT10/TE11 Stevens MRT",
    amount: "6800000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-balmoral-8-25028136",
    about:
      '"About this property: Beautifully renovated penthouse! Move in condition! Vacant possession! Rare Duplex Penthouse in Balmoral 8 for sale! Motivated seller. Selling vacant Possession! Move in condition. Nicely done up roof terrace! 3 ensuite bedrooms! Private lift access with spacious living and dining room! Great perpetual unblock view! -1km with ACS Barker- 1.03km within SCGS - 1km proximity to ACS and SCGS Contact Geraldine @ 9731… for an exclusive viewing! Dont miss this opportunity!!"',
    bed: 4,
    bath: 5,
    sqft: "3758",
    psf: "S$ 1,809",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "3b82148f-fb75-4cd2-a2af-9e8fe1aa52c6",
    title: "Freehold 4 Bedroom for Sale",
    code: "DEPARTMENT-29",
    address: "Tanglin / Holland / Bukit Timah (D10)",
    distance: "11 mins (900 m) from CC20 Farrer Road MRT",
    amount: "7770000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-freehold-4-bedroom-for-sale-25066219",
    about:
      '"About this property: Immense Sized Luxury Property for Sale. Welcome to this stunning 4 bedroom, 4 bathroom condominium in District 10. With a spacious 2659 sqft of living space, this property offers luxury and comfort in a prime location. Nearby Amenities: - Holland Village Subway Station (Distance: 0.8 km) - Farrer Road Subway Station (Distance: 1.2 km) - C Licence Pte Ltd School (Distance: 0.4 km) - Swim Centre Verhoef School (Distance: 0.6 km) - CS Fresh @ Holland Shopping Centre Supermarket (Distance: 0.6 km) - CS Fresh One Holland Village Supermarket (Distance: 0.4 km) - Casa de muñecas Shopping Mall (Distance: 0.5 km) - Empress Mall Shopping Mall (Distance: 0.7 km) Don\'t miss the opportunity to own this beautiful condominium with easy access to nearby schools, supermarkets, shopping malls, and MRT stations. Contact us at 8101*7777 today for a viewing!"',
    bed: 4,
    bath: 4,
    sqft: "2659",
    psf: "S$ 2,922",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "44ed1698-0c4c-49c9-9a11-5dbb963d1276",
    title: "Stratum",
    code: "DEPARTMENT-4",
    address: "98 Elias Road Pasir Ris / Tampines (D18)",
    distance: "9 mins (740 m) from CP2 Elias MRT",
    amount: "700000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-stratum-24972686",
    about:
      '"About this propertyBest stack. True north south facing.Studio unit for saleGood size unit with kitchen, bathroom and balconyUnit can fit a Queen size bed and a sofa set, with study table at the other cornerTrue north south facing, very breezy and no warm afternoon sunGreenery viewOnly block for Studio units with direct carpark accessStratum is just a 5 minutes walk to Pasir Ris beach, 5 mins bus ride to Pasir Ris MRT, Bus interchange and White sands shopping mall.5 minutes walk to future Cross island line, Elias MRT StationCall William now at          9*****         for a viewing arrangement Show more"',
    bed: 2,
    bath: 1,
    sqft: "452",
    psf: "S$ 1,549",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "49dc344b-11ae-4912-bdc6-ae1e91f54c5a",
    title: "312 Hougang Avenue 5",
    code: "DEPARTMENT-12",
    address: "312 Hougang Avenue 5 Hougang / Punggol / Sengkang (D19)",
    distance: "11 mins (940 m) from CR7 Defu MRT",
    amount: "1080000",
    link: "https://www.propertyguru.com.sg/listing/hdb-for-sale-312-hougang-avenue-5-25062637",
    about:
      '"About this propertySuper Rare Landed Feeling Maisonette!- Super Rare Maisonette Unit - Nestled in the Landed Enclave for peaceful and tranquil environment - Comes with an outdoor Patio area, which can be converted to become an extension of your dining area. - Able to do Open Concept Kitchen- Bright and Breezy Unit - Spacious Rectangular Layout- Able to convert dining area into 4th Bedroom - All 3 Bedrooms Intact- Top & Bottom Cabinet in Kitchen - Main Door SE - Facing open space unblocked- Back Door opens to HaiSing Crescent 1min walk - Eateries and Supermarket at Hougang Rivercourt just within walking distance - Closeby promiximity to Hougang Community Centre - Fully Sheltered walkway all the way to bus stops - Eateries and Amenities all within walking distance, just 2 blocks away - A few bus stops away  from Hougang MRT, Hougang Bus Interchange & Hougang Mall1 bus stop to Hougang MRT/bus interchange from Ave 5 Blk 308Viewing by Appointment , Contact Jason to arrange for an exclusive viewing. Whether you are looking to buy or sell, we are here to guide and advise you. Show more"',
    bed: 3,
    bath: 2,
    sqft: "1474",
    psf: "S$ 733",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "57b1206b-9f13-46f2-8812-2de31557b7e1",
    title: "The Botany at Dairy Farm",
    code: "DEPARTMENT-34",
    address:
      "3 Dairy Farm Walk Dairy Farm / Bukit Panjang / Choa Chu Kang (D23)",
    distance: "9 mins (780 m) from DT3 Hillview MRT",
    amount: "2908000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-the-botany-at-dairy-farm-25099438",
    about:
      '"About this property: Up To $125k Discount. Click To Find Out More Here. Genuine Price No Commission Payable. Enjoy Up To $125,000 Direct Discount. RECEIVE FULL LATEST PRICE LIST* The Botany at Dairy Farm * to +65 9_0_4_8 0_6_6_0 *The development will have around 385 residential units and is situated on a 1.56-hectare site. It is surrounded by greenery, with the 75-hectare Dairy Farm Nature Park right at its doorstep Developer: Sim Lian Group. Location: Along Dairy Farm Walk, next to German European School Singapore. Tenure: 99-year leasehold Units: 386 residential units ranging from 1 to 5 bedrooms Amenities: Close to Hillview MRT, shopping centers like HillV2 and Rail Mall, and upcoming Dairy Farm Mall The Latest Prestigious FREEHOLD D10 Development Located at the much sought-after address – Orchard Boulevard ** Pls Call Direct Developer Sales @ +65 9_0_4_8 0_6_6_0 For More Info ** One Call View All! Daily Viewing! * CALL FOR DIRECT DEVELOPER SALES ENQUIRY & PRICING / Daily Appointment. +6***** * + 开发商指定经纪 | 嘉宾预购可享特价优惠+ 首选单位，优惠价格，考查发展项目 |请拨热线开发商销售热线 +65 9_0_4_8 0_6_6_0"',
    bed: 4,
    bath: 3,
    sqft: "1,539",
    psf: "S$ 1,890",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "59be1c57-2c42-4ec6-a7a2-ae7565b56d79",
    title: "Joo Chiat Terrace",
    code: "DEPARTMENT-6",
    address: "78 Joo Chiat Terrace East Coast / Marine Parade (D15)",
    distance: "8 mins (650 m) from EW7 Eunos MRT",
    amount: "3500000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-joo-chiat-terrace-25083806",
    about:
      '"About this propertyRare Freehold Residential Shophouse on Sale! Currently Vacant! Exclusive FREEHOLD landed conserved shophouse unit vacant up for sale! * Cover image virtually staged for impression purpose*️ Highly accessible to city central, town, East Coast Park, and Changi Airport via PIE expressway. Only a mere 5 minutes to Eunos MRT! ️ Located in District 15 and heart of Joo Chiat, enjoy the rich local heritage with an abundance of food outlets, cafes, restaurants, and traditional food eateries and coffee shops. You may also wish to visit the nearest malls at i12, Katong Village, Parkway Parade or Katong Shopping Centre! ️ Best for parents with kids looking to have close proximity to schools, within 1km to 2km from CHIJ Katong Pri, Kong Hwa Sch, Geylang Methodist Pri, and Maha Bodhi Sch etc.️ Unleash your creativity and passion for interior design by planning and designing your own space, engaging in Addition and Alteration of the unit to transform it into a homely space!️ Enjoy the pristine and band new roof installed in 2021, covering the unit from the sun and protecting from Singapore\'s torrential weather.️ Most importantly, it is a FREEHOLD unit, hence a perfect location for you to make it a place for your own home, or even convert it to a long term investment unit for your and your loved ones and subsequent generations! Contact Melvin Lee at          8*****         today! Show more"',
    bed: 5,
    bath: 2,
    sqft: "1772",
    psf: "S$ 1,975",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "5d6faebd-e793-4a6f-891d-4f01ca692c7e",
    title: "The Vantage",
    code: "DEPARTMENT-35",
    address: "6 Orange Grove Road Tanglin / Holland / Bukit Timah (D10)",
    distance: "10 mins (860 m) from NS22/TE14 Orchard MRT",
    amount: "15000000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-the-vantage-24977239",
    about:
      "\"About this property: Rare Prime Area, Near Amenities Yet Tranquil At The Vantage! CEA Registration: L3010858B / R029908E Introducing a rare find in the coveted Orange Grove, Ardmore area – a sprawling duplex unit offering a lavish 5770 sqft floor plan. Nestled amidst prime real estate, this residence perfectly balances proximity to amenities with the tranquility of quiet living. Boasting 4 bedrooms, 4 bathrooms, a balcony, and a maid's room, this corner unit exudes luxury and comfort. This renovated low-floor gem features breathtaking city views and a convenient northeast-facing main door orientation. Convenience is key with just a 2-minute stroll to the nearest bus stop, supermarket, and eateries, while the nearest MRT station is a mere 10-minute walk away. Families will appreciate the proximity to renowned educational institutions such as Raffles Girls' School, ISS International School, and more. Don't miss this exceptional opportunity to secure a spacious, well-appointed residence in one of Singapore's most sought-after neighborhoods, offering both convenience and value. Exclusive Propseller Listing! Size: - 5770 sqft. - 4 bedrooms + 4 bathrooms - Balcony, Maid's Room Attributes: - Extension needed: None - Unit orientation: Corner unit - Low-floor unit - Renovated condition - Main door facing North-East - Views from unit: City Convenience: - 2 min walk to the nearest bus stop (bus services: 7, 36, 77, 105, etc.) - 1 min walk to the nearest supermarket - 1 min walk to the nearest eateries - 10 min walk to Orchard MRT - Schools within 1 km: Raffles Girls' School, ISS International(Elementary & Middle), and more. - Schools within 2 km: Singapore Chinese Girls' Primary, Chinese International, and more.\"",
    bed: 4,
    bath: 4,
    sqft: "5770",
    psf: "S$ 2,600",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "5efbf849-48b6-4813-9ae2-1d506398e4fe",
    title: "Queens",
    code: "DEPARTMENT-32",
    address: "10 Stirling Road Alexandra / Commonwealth (D03)",
    distance: "3 mins (210 m) from EW19 Queenstown MRT",
    amount: "2580000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-queens-25015878",
    about:
      '"About this property: Very good size 4-bedroom - Spacious 4 bedroom, 4 bathroom condominium located at 10 Stirling Road, Singapore - Approximately 1410 sqft of living space for comfortable living - Just a short walk to Queenstown MRT station, providing easy access to the rest of Singapore - Close proximity to reputable schools such as Anglo-Chinese School (International) and MDIS UniCampus - Conveniently located near NTUC FairPrice supermarket for all your grocery needs - Enjoy shopping at nearby malls like Anchorpoint Shopping Centre and IKEA Alexandra - Well-maintained development with top-notch facilities including swimming pool, gym, and playground - Ideal for families looking for a modern and convenient living space in a prime location"',
    bed: 4,
    bath: 4,
    sqft: "1410",
    psf: "S$ 1,830",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "602a0bc7-36a2-4218-8237-c6bfc037c524",
    title: "Ascentia Sky",
    code: "DEPARTMENT-3",
    address: "3 Alexandra View Alexandra / Commonwealth (D03)",
    distance: "4 mins (310 m) from EW18 Redhill MRT",
    amount: "2900000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-ascentia-sky-25094547",
    about:
      '"About this propertySuper high floor unblocked viewRare sale! Super super high floor!Rare large floor plate in a prime location.Cobroke 50/50.Pure selling no extension required.Owner selling below valuation.Unit details:Size: 1475 sqft3 Bedrooms + 2 bath + toilet + store roomOriginal conditionPrefect North-south facingNo west sunSuper breezyFull condo facilities including tennis courtVideo available upon requestAround the vicinity:Redhill Mrt: 100mBus stop: 70mAlexandra Pri School: within 1kmGan Eng Seng Pri School: within 1kmRadin Mas Pri School: within 1-2kmZhangde Pri School: within 1-2kmMore than 15 childcare centres within walking distanceGreat World City, Tiong Bahru Plaza, GIANT & NTUC all within walking distance.Connect with Alvin today to secure this magnificent unit asap before it\'s taken.Cobroke welcome 50/50. Show more"',
    bed: 3,
    bath: 3,
    sqft: "1475",
    psf: "S$ 1,966",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "61ffbbfa-b47a-4abc-9aa4-1f63fb4918f6",
    title: "2.5 storey peranakan inspired terrace",
    code: "DEPARTMENT-8",
    address:
      "Terang Bulan Avenue/Opera estate East Coast / Marine Parade (D15)",
    distance: "20 mins (1.6 km) from EW5 Bedok MRT",
    amount: "4600000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-2-5-storey-peranakan-inspired-terrace-24335929",
    about:
      '"About this property2.5 storey peranakan inspired terraceSimple touch up to move in.. Exceptionally well-kept by current owner. Feature of the house 1) Non-door to door facing.2) Living Room open to a lovely covered patio for breakfast. 3) Good size kitchen for hosting friend and cover wet kitchen for heavy cooking. 4) north/south facing 5) Internal Airwell for airflow circulation within the house. Cooling even without opening the window6) Airwell act as a lift shaft for buyer whom looking to install lift 7) bathroom with natural ventilation 8) Sizeable room that fit King bed 9) East access to Chai Chee coffeeshop, Wet market, walk to Bedok mrt 10) Close to 2000sqft of land make it a comfortable size TerraceAvg local Bank Indicative 4.7-4.8mWeekday viewing PreferDisclaimer: Information on this listing shall not constitute or construct as any commitment or warranty of the property. All measurement stated are subject to final survey. Show more"',
    bed: 5,
    bath: 4,
    sqft: "1991",
    psf: "S$ 2,310",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "6bdb4996-6592-4759-8c02-e74bf9dc2fef",
    title: "Daintree Residence",
    code: "DEPARTMENT-38",
    address: "11L Toh Tuck Road Clementi Park / Upper Bukit Timah (D21)",
    distance: "10 mins (800 m) from DT5 Beauty World MRT",
    amount: "2100000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-daintree-residence-24924814",
    about:
      "\"About this property: Luxurious Living With High-End Finishes And Exceptional Features! Preview in virtual tour: www.h***** Indulge in the epitome of luxury with this 3-bedroom unit spanning 1001 sqft, featuring exquisite kitchen appliances by De Dietrich, elegant marble flooring, and an impressive 4.3m high ceiling. Beyond the standard, this well-renovated ground floor unit offers a unique blend of sophistication and comfort. Enjoy the seamless flow of natural light and air in this corridor unit, with the main door facing east and south, offering picturesque landscape views. The unit boasts a balcony and a study for added versatility in living spaces. Convenience is parprice, with a 1-minute walk to the nearest bus stop and a short 6-minute stroll to both supermarkets and eateries. For those who appreciate accessibility, Beauty World MRT is just a 10-minute walk away, providing seamless connectivity. Families will appreciate the proximity to esteemed schools, with Bukit Timah Primary and Pei Hwa Presbyterian Primary within 1 km and other educational institutions within 1-2 km. Elevate your lifestyle with this exceptional residence that seamlessly combines high-end finishes, thoughtful design, and unparalleled convenience. Don't miss the opportunity and book a viewing with us today. Exclusive Propseller Listing! Size: - 1001 sqft. - 4 bedrooms + 2 bathrooms - Balcony Attributes: - Extension needed: None - Unit orientation: Corridor unit - Ground floor unit - Well Renovated condition - Main door facing - East, South - Views from unit: Landscape - High Ceiling Convenience: - 1 min walk to the nearest bus stop (bus services: 41, 77, 173) - 6 mins walk to the nearest supermarket - 6 mins walk to the nearest eateries - 10 mins walk to Beauty World MRT - Schools within 1 km: Bukit Timah Primary and Pei Hwa Presbyterian Primary. - Schools within 1-2 km: Bukit View Primary, Keming Primary, and Methodist Girls' School (Primary).\"",
    bed: 4,
    bath: 2,
    sqft: "1001",
    psf: "S$ 2,098",
    createdAt: "2024-06-21T05:48:58.000Z",
    updatedAt: "2024-06-21T05:48:58.000Z",
    deletedAt: null,
  },
  {
    id: "6c072756-9df1-4d07-8a14-02b83c61bf5e",
    title: "Nathan Suites",
    code: "DEPARTMENT-42",
    address: "21 Nathan Road Tanglin / Holland / Bukit Timah (D10)",
    distance: "12 mins (970 m) from TE15 Great World MRT",
    amount: "4800000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-nathan-suites-24820115",
    about:
      '"About this property: Freehold 4 bedrooms in D09-Freehold -65 Units in this Exclusive Development-Exclusive Private Lift For All Units-High floor-Fully Furnished with Luxury Brands from Gaggenau, Laufen -Equipped with both Wet and Dry Kitchen-Excellent Cross Ventilation-Minutes Drive to Orchard Road. Singapore’s Premiere  Shopping Belt-Short Drive to Orchard Road/ Central Business -District (CBD) & Marina Bay Sands (MBS)-Walking distance to River Valley Road – For  amenities & popular food eateriesNathan Suites is a freehold condominium development nestled on Nathan Road, within the highly affluent neighbourhood of District 10.  As Nathan Suites is strategically located, it is never short of access to conveniences most of which are within close distance, such as shopping malls, banking services, food and many more. Within the distances are also many reputable schools both local and international for those with school going children. Nathan Suites is within close proximity to Tiong Bahru and Orchard MRT stations.  In addition, as it is conveniently located it is easily accessible and is within close distance to Tiong Bahru and Orchard MRT stations. Not to mention, also easy availability of public buses and taxis. Nathan Suites offers its residents full condo facilities that is only exclusively for the residents’ enjoyment. These communal facilities include:--Function room with kitchen-Steam rooms-Gym-Lap pool, Splash pool, Hydrotheraphy pool-Water hammocks-BBQ/Dining Pavilion-Playground-Fitness corner -Suntan decks, -feature gardens-Yoga deck  Don’t miss! Kindly call or Whatsapp Mindy  @ 9***** for an exclusive viewing now! Show more"',
    bed: 4,
    bath: 4,
    sqft: "2024",
    psf: "S$ 2,372",
    createdAt: "2024-06-21T05:48:58.000Z",
    updatedAt: "2024-06-21T05:48:58.000Z",
    deletedAt: null,
  },
  {
    id: "6dd84655-ce44-4847-a851-b91ae2a02b99",
    title: "Grange Residences",
    code: "DEPARTMENT-33",
    address: "91 Grange Road Tanglin / Holland / Bukit Timah (D10)",
    distance: "5 mins (450 m) from TE13 Orchard Boulevard MRT",
    amount: "8800000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-grange-residences-23892280",
    about:
      '"About this property: Freehold; Prestigious Grange Road. **New Listing For Sale** Great Investment Unit! 2584sqft Renovated Unit Tenanted until January 2025 to a European MNC Super convenient location close to Orchard Road, Botanical Gardens, and Dempsey. Right opposite Tanglin Mall and Camden Medical. - Above 5th floor Unit - Private Lift Lobby - 4 bedrooms - Helper’s Room with en-suite Bathroom - 4 bathrooms 3 en-suite 1 powder room - Entire Aircon system replaced - Bathroom and kitchen recently renovated with new appliances - Entire unit recently painted and upgraded - Plenty of storage spaces - Wet and Dry Kitchen with Aircon Facilities include covered car park, 24h security, kids pool, swimming pool, tennis court, recently renovated gym, and recently upgraded playground area. Kindly call Vashty for exclusive viewing appointments! ——— **新上市待售** 华丽的投资单位！ 2584平方尺租借至2025年1月欧洲跨国公司 地理位置优越，靠近果园路、植物园和邓普西 唐林商场及康登医疗对面 - 五楼以上单位 - 私人升降机大堂 - 4间卧室 - 带浴室的服务员室 - 更换整个空调系统 - 浴室和厨房最近用新电器翻新 - 整个单位最近粉刷和升级 - 充足的储存空间 - 干湿厨房加空调 设施包括有盖停车场、24小时保安、儿童游泳池、游泳池、网球场、最近翻修的健身房和最近升级的游乐场。 欢迎致电 Jasmine Ye 预约独家观看!"',
    bed: 4,
    bath: 4,
    sqft: "2583",
    psf: "S$ 3,407",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "717b330e-96c4-48bc-9b37-8d6ed27457d0",
    title: "Nine Residences",
    code: "DEPARTMENT-43",
    address: "Yishun Avenue 9 Sembawang / Yishun (D27)",
    distance: "18 mins (1.5 km) from NS13 Yishun MRT",
    amount: "1550000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-nine-residences-24976206",
    about:
      '"About this property: Contact us today to make an enquiry. New listing. Nine Residences Commercial residence. Shops and amenities are all within reach. Pool view Nearby EC ALREADY SOLD at $1438 psf as at Apr 2022. North Park Residence at central already hit $1751 May 2022. Are you waiting for the price to go further? Discover a gem before the whole Yishun Transformation. Junction Nine Shopping Mall below with amenities and eateries. Primary School: - Xi Shan Primary - Chongfu School - Huamin Primary - Yishun Primary - Ahmad Ibrahim Primary. Secondary School: - Northland Secondary - Yishun Town Secondary - North View Secondary. Show more"',
    bed: 4,
    bath: 3,
    sqft: "1173",
    psf: "S$ 1,321",
    createdAt: "2024-06-21T05:48:58.000Z",
    updatedAt: "2024-06-21T05:48:58.000Z",
    deletedAt: null,
  },
  {
    id: "7785aed2-637b-4ce0-9420-67ba6b819947",
    title: "10A Bendemeer Road",
    code: "DEPARTMENT-11",
    address: "Bendemeer Road Balestier / Toa Payoh (D12)",
    distance: "5 mins (390 m) from DT23 Bendemeer MRT",
    amount: "1120000",
    link: "https://www.propertyguru.com.sg/listing/hdb-for-sale-10a-bendemeer-road-25089303",
    about:
      '"About this propertyR A R E! S U P E R. H I G H. F L O O R!. Mins walk to Bendemeer MRT!RARE! RENOVATED! SUPER HIGH FLOOR!Enjoy unblocked city views from this apartment in an unparalleled, exceptional city fringe location!Experience the city living convenience of 5 mins Walk to Bendemeer MRT & 7 mins walk to Boon Keng MRT and many nearby malls!Delightful Modern Interiors, designed with timeless comfort & harmony, perfect for a modern family!- Spacious Elegant Living & Dining with plenty of space for the family to spend quality time together - Open concept Dry Kitchen with beautiful kitchen island, perfect for morning coffee!- Functional Wet Kitchen with lots of counter top space & cabinets for storage - Master Bedroom with King Size beds and bedside tables, a cozy & romantic sanctuary to refresh & rejuvenate after a long day’s work  - Bedroom 2 is a nursery and baby room, designed for the young one to rest and relax- Bedroom 3 is a multi-purpose room, fulfilling the family’s various needs from a study/home office, exercise/yoga room to a music room while having a visual connection with the main living & dining spaces- Bathrooms are well-maintained & in superb conditionNear many shopping & dining amenities in nearby malls such as City Square Mall, Aperia Mall, Bendemeer Shopping Mall, Centrium Square & Mustafa Centre!Within 1 km to Hong Wen School, Bendemeer Primary & Farrer Park Primary! Within 2 km to St Andrew’s Junior & Secondary, St Jospeh’s Institution Junior, St Margaret’s School! Do Not Miss! Call Gilda          9*****         for an exclusive viewings NOW! Show more"',
    bed: 3,
    bath: 2,
    sqft: "1001",
    psf: "S$ 1,119",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "804d0d57-54fa-484f-8226-3b4d291c009e",
    title: "Regent Heights",
    code: "DEPARTMENT-41",
    address:
      "50 Bukit Batok East Avenue 5 Dairy Farm / Bukit Panjang / Choa Chu Kang (D23)",
    distance: "12 mins (1 km) from NS2 Bukit Batok MRT",
    amount: "2800000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-regent-heights-25060869",
    about:
      '"About this property: Contact us today to make an enquiryRare listingIncredible size above 2500sqft5 bedroom + 1 entertainment roomPossibility to adopt dual key conceptMaximum usable living areaNO ROOF TERRACEUnblocked Panoramic viewWindy house with natural lightTastefully renovated and designedClose to amenitiesShort distance to MRTClose to primary schoolsSee to believe.Call 8***** for viewing✨ I am Jowell, let\'s make you do well! ❣#property #propertyneeds #homesales#househunting #homeswithvalue#ProperProperty #sgproperty#propertyinfo #singapore #ACCEDEframework #aceprudencytest #PropertyWellnessCollective#daddypropertychef#diaryofapropertyagent#bringingyoutoabetterposition Show more"',
    bed: 6,
    bath: 5,
    sqft: "2594",
    psf: "S$ 1,079",
    createdAt: "2024-06-21T05:48:58.000Z",
    updatedAt: "2024-06-21T05:48:58.000Z",
    deletedAt: null,
  },
  {
    id: "838d5d6c-aac4-42b3-88f5-8f5ab5c30ae1",
    title: "Nathan Suites",
    code: "DEPARTMENT-39",
    address: "21 Nathan Road Tanglin / Holland / Bukit Timah (D10)",
    distance: "12 mins (970 m) from TE15 Great World MRT",
    amount: "4800000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-nathan-suites-24820115",
    about:
      '"About this property: Freehold 4 bedrooms in D09-Freehold -65 Units in this Exclusive Development-Exclusive Private Lift For All Units-High floor-Fully Furnished with Luxury Brands from Gaggenau, Laufen -Equipped with both Wet and Dry Kitchen-Excellent Cross Ventilation-Minutes Drive to Orchard Road. Singapore’s Premiere  Shopping Belt-Short Drive to Orchard Road/ Central Business -District (CBD) & Marina Bay Sands (MBS)-Walking distance to River Valley Road – For  amenities & popular food eateries Nathan Suites is a freehold condominium development nestled on Nathan Road, within the highly affluent neighbourhood of District 10.  As Nathan Suites is strategically located, it is never short of access to conveniences most of which are within close distance, such as shopping malls, banking services, food and many more. Within the distances are also many reputable schools both local and international for those with school going children. Nathan Suites is within close proximity to Tiong Bahru and Orchard MRT stations.  In addition, as it is conveniently located it is easily accessible and is within close distance to Tiong Bahru and Orchard MRT stations. Not to mention, also easy availability of public buses and taxis. Nathan Suites offers its residents full condo facilities that is only exclusively for the residents’ enjoyment. These communal facilities include:-- Function room with kitchen- Steam rooms- Gym- Lap pool, Splash pool, Hydrotheraphy pool- Water hammocks- BBQ/Dining Pavilion- Playground- Fitness corner - Suntan decks, - feature gardens- Yoga deck  Don’t miss! Kindly call or Whatsapp Mindy  @ 9***** for an exclusive viewing now!"',
    bed: 4,
    bath: 4,
    sqft: "2024",
    psf: "S$ 2,372",
    createdAt: "2024-06-21T05:48:58.000Z",
    updatedAt: "2024-06-21T05:48:58.000Z",
    deletedAt: null,
  },
  {
    id: "87580d8d-6184-47c6-a6b2-a7865e12ac8d",
    title: "Queens",
    code: "DEPARTMENT-31",
    address: "10 Stirling Road Alexandra / Commonwealth (D03)",
    distance: "3 mins (210 m) from EW19 Queenstown MRT",
    amount: "2580000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-queens-25015878",
    about:
      '"About this property: Very good size 4-bedroom - Spacious 4 bedroom, 4 bathroom condominium located at 10 Stirling Road, Singapore - Approximately 1410 sqft of living space for comfortable living - Just a short walk to Queenstown MRT station, providing easy access to the rest of Singapore - Close proximity to reputable schools such as Anglo-Chinese School (International) and MDIS UniCampus - Conveniently located near NTUC FairPrice supermarket for all your grocery needs - Enjoy shopping at nearby malls like Anchorpoint Shopping Centre and IKEA Alexandra - Well-maintained development with top-notch facilities including swimming pool, gym, and playground - Ideal for families looking for a modern and convenient living space in a prime location"',
    bed: 4,
    bath: 4,
    sqft: "1410",
    psf: "S$ 1,830",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "8a907232-326b-49c2-88d3-f1eb9be23f70",
    title: "The Windsor",
    code: "DEPARTMENT-17",
    address: "9A Ontario Avenue Ang Mo Kio / Bishan / Thomson (D20)",
    distance: "10 mins (850 m) from TE7/CR13 Bright Hill MRT",
    amount: "2640000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-the-windsor-24249637",
    about:
      '"About this propertyFreehold, Pool Facing, Walk up!New Listing!*Separate living n Dinning Hall *Spacious size all bedrooms*Living n Master Bedroom facing pool view*Walking distance to Thomson Plaza*Full condo facilities *Walk up unitCall          9*****         for exclusive viewing Show more"',
    bed: 3,
    bath: 2,
    sqft: "1625",
    psf: "S$ 1,625",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "9883903e-b06f-4074-8a1c-d8f7ab37d03d",
    title: "Nine Residences",
    code: "DEPARTMENT-40",
    address: "Yishun Avenue 9 Sembawang / Yishun (D27)",
    distance: "18 mins (1.5 km) from NS13 Yishun MRT",
    amount: "1550000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-nine-residences-24976206",
    about:
      '"About this property: Contact us today to make an enquiryNew listingNine ResidencesCommercial residenceShops and amenities are all within reach.Pool view Nearby EC ALREADY SOLD at $1438 psf as at Apr 2022North Park Residence at central already hit $1751 May 2022Are you waiting for the price to go further?Discover a gem before the whole Yishun TransformationJunction Nine Shopping Mall below with amenities and eateriesPrimary School:✔ Xi Shan Primary✔ Chongfu School✔ Huamin Primary✔ Yishun Primary✔ Ahmad Ibrahim PrimarySecondary School:✔ Northland Secondary✔ Yishun Town Secondary✔ North View Secondary Show more"',
    bed: 4,
    bath: 3,
    sqft: "1173",
    psf: "S$ 1,321",
    createdAt: "2024-06-21T05:48:58.000Z",
    updatedAt: "2024-06-21T05:48:58.000Z",
    deletedAt: null,
  },
  {
    id: "9dcb31d0-633d-4473-8c40-127adc4f7cfd",
    title: "664A Punggol Drive",
    code: "DEPARTMENT-14",
    address: "664A Punggol Drive Hougang / Punggol / Sengkang (D19)",
    distance: "4 mins (310 m) from PE5 Kadaloor LRT",
    amount: "650000",
    link: "https://www.propertyguru.com.sg/listing/hdb-for-sale-664a-punggol-drive-24958994",
    about:
      '"About this property4 Rm For Sale, Move-in Condition→ 4-Rm Model A Flat (90 sqm / 968 sq ft)→ Mid Floor, Bright & Airy→ 3 Bedroom, 2 Bathroom→ Move-in Condition→ Squarish & Efficient Size→ All Ethnic Welcome→ No Extension Required, Pure Selling→ Door-Step to Kadaloor LRT Station→ Near to Punggol Plaza→ Near to Punggol PolyclinicNearby Schools:• Waterway Primary• Horizon Primary• Oasis Primary• Edgefield Primary• Greendale Primary• Greendale Secondary• Punggol SecondaryCall John Yeo at          9*****         For An Exclusive Viewing Today! Show more"',
    bed: 3,
    bath: 2,
    sqft: "968",
    psf: "S$ 671",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "a15725cb-e706-41a1-a959-7f8ab4d12f30",
    title: "Duchess Manor",
    code: "DEPARTMENT-19",
    address: "20 Duchess Road Tanglin / Holland / Bukit Timah (D10)",
    distance: "11 mins (950 m) from DT8 Tan Kah Kee MRT",
    amount: "4250000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-duchess-manor-24601025",
    about:
      '"About this propertyRare Penthouse for Sale in D10Four bedroom duplex penthouse for Sale.-1km to Nanyang Primary & Raffles Girls\' Primary.-5 minutes walk to Tan Kah Kee MRT station (DT8).-12min walk to Botanical Gardens.1st floor live-in space approx. 1700sqft 2nd floor outdoor space approx. 1600sqft -Keys on hand can view anytime.-Rarely available.Co-broke welcomeContact Simon Hum at 9***** for viewing today. Show more"',
    bed: 4,
    bath: 3,
    sqft: "3218",
    psf: "S$ 1,321",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "a1696a00-7293-4b62-8cf3-37b7075b8cab",
    title: "Freehold Semi Detached @ Eaton Walk",
    code: "DEPARTMENT-15",
    address: "Eaton walk/Yio Chu Kang Road Seletar / Yio Chu Kang (D28)",
    distance: "8 mins (700 m) from SW5 Fernvale LRT",
    amount: "4380000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-freehold-semi-detached-eaton-walk-24546382",
    about:
      '"About this propertyD28 semi detached house for sale!Freehold 2 storey semi detached house for sale! Rarely available in Eaton Walk. Well kept house with Cozy Decor.  5 Bedrooms, helper s room n       Store rooms. 3 Bathrooms n a powder room. Quiet Ambience. Bright and Breezy. Nice layout, Spacious master       room with large balcony for family       Bonding n entertainment. Accessible to Public Transports n       Malls. View to Appreciate! Motivated Sellers!Don’t Miss! Please contact Jess @          9*****        for viewings! Show more"',
    bed: 5,
    bath: 4,
    sqft: "2,153",
    psf: "S$ 2,034",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "ad067e44-2649-4572-8247-386dff48eec1",
    title: "The Red House",
    code: "DEPARTMENT-9",
    address: "63 East Coast Road East Coast / Marine Parade (D15)",
    distance: "6 mins (530 m) from TE26 Marine Parade MRT",
    amount: "1150000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-the-red-house-24959189",
    about:
      "\"About this propertyRare Maisonette 1 Bedroom Suite Nestled in a Conservation Building◆ Apartment For Sale ◆ The Red House, Maisonette 1 Bedroom Suite【 Unit Details 】- 63 East Coast Road Singapore 428776- Floor Area: 764 sqft- 1 Bedroom, 1 Bath- Asking from $1,150,000, $1,505 psf- Monthly Maintenance Approximately $423.70- Selling with Vacant Possession- High Ceiling, Designer Unit, Fully Furnished- Well-kept unit condition - Efficient layout - Spacious layout - Regular layout for furniture placement - Bright and airy - Close to upcoming MRT, Convenient location - Convenient location - Swimming pool and gym- Good for investment and own stay【 Development Details 】- Tenure: 99 Years from 06/01/2012- Completion / TOP: 2016- District: 15 | 1,583 sqm- Land Size: 17,042 sqft- Total Number of Units: 42 Residential Units, 5 Commercial Units and a Bakery- Developer: WRH Pte. Ltd【 Other Details 】- A limited edition, integrated heritage development composed of distinctive residences situated within Katong’s most historical landmark – The Red House Bakery.- Boutique Development with Swimming Pool and Gym- Consisting 6 Conservation Shops, 5-storey Residential Annex Block- Shops, Eateries, Amenities and East Coast Park nearby- 5 mins walk to upcoming Marine Parade MRT Station (Thomson-East Coast Line)- Bus Services to CBD, Orchard, Suntec, Bugis, Cityhall- 20 mins bus services to CBD (Shenton Way & Raffles Place)【 Connectivity 】⭑ MRT STATIONS ⭑- Marine Parade - TE26 (0.35 km)【 Convenience 】⭑ SHOPPING MALLS ⭑- Katong V (0.16 km)- 112 Katong (0.21 km)- Parkway Parade (0.40 km)【 Schools Nearby 】- Tanjong Katong Primary School (0.37 km)- Chatsworth International School East Campus (0.57 km)- Canadian International School - Tanjong Katong Campus (0.68 km)- Haig Girls' School (0.75 km)- Tanjong Katong Secondary School (0.78 km)- CHIJ (katong) Primary (0.86 km)- Tanjong Katong Girls' School (0.86 km)- CHIJ (katong) Primary (0.86 km)- Tao Nan School (0.90 km)Sherry Tang | AsianPrime Properties Show more\"",
    bed: 1,
    bath: 1,
    sqft: "764",
    psf: "S$ 1,505",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "c0769207-cad1-4061-ae4f-e0d14a90f4de",
    title: "Best value new built in Whitley",
    code: "DEPARTMENT-26",
    address: "Newton / Novena (D11)",
    distance: "14 mins (1.2 km) from NS20 Novena MRT",
    amount: "7300000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-best-value-new-built-in-whitley-24994574",
    about:
      '"About this property: Best value buy Semi D in District 11. New built by Eminence Landed Team. Land: 2174sqft Built up: 4684 TOP Obtained! Last 3! D11 Brand New Semi-D in Prestigious landed estate. Land: 2174sqft Built-Up: 4684Sqft"',
    bed: 2,
    bath: 2,
    sqft: "2174",
    psf: "S$ 3,358",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "cf242eac-a93d-49b2-8d84-c7343e7177a0",
    title: "Riverfront Residences",
    code: "DEPARTMENT-5",
    address: "53 Hougang Avenue 7 Hougang / Punggol / Sengkang (D19)",
    distance: "17 mins (1.4 km) from NE14/CR8 Hougang MRT",
    amount: "1699000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-riverfront-residences-25015773",
    about:
      '"About this propertyExcellent pool facing high floor brand new vacant 3 bedder unit! One of the BEST stacks of 3 bedroom 2 bathroom units in entire development! View to appreciate!!!- Quiet and peaceful enjoyment of the pool view without the noise!- Great privacy- Efficient layoutABOUT UNIT- Serious seller- Immediately ready to move in- High floor- Corner unit- No direct west sun- Unit is literally situated in the middle of all facilities!- Very reasonably priced at valuation!ABOUT DEVELOPMENT- Award winning architect!- 3 swimming pools!- Smart home! All bookings simply through your mobile phone!- Convenience at door step with 6 retail units in development!- Multiple retail malls within stone’s throw away!- Hougang MRT station within a short stroll away!- Shuttle bus service to Hougang Central provided as well!- Mega development= great price protection and investment opportunity!Primary Schools within 1 km-CHIJ Our lady of the Nativity-Holy Innocents’ Primary School-Punggol Primary SchoolChildcare nearby-Star Learners, Xavier’s Lane-Blossom Educare Centre, Lorong Batawi-E-Bridge Pre School, 365B Upper Serangoon Road-Junior Playworld Child Care & Development Centre, Jalan Lye Kwee-And many moreSupermarkets-NTUC Fairprice, 100 Hougang Avenue 10-NTUC Fairprice, 476 Upper Serangoon View-Chop Ah Tat Mini Supermarket, 309 Hougang Avenue 5Other amenities- Coffeeshop, 7-11, dental clinic, medical clinic and other retails shops just within 5 minutes walk away at block 356 Hougang Avenue 7!- Punggol Park just a traffic junction away!Why compromise your lifestyle and property choice by choosing lower floors or bad facing stacks!?Contact me at          8*****         for exclusive viewing or if you require more information! Show more"',
    bed: 3,
    bath: 2,
    sqft: "915",
    psf: "S$ 1,857",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "d76c93b3-7d17-4d86-ab9e-5dd781889eb8",
    title: "Parkwood Collection",
    code: "DEPARTMENT-23",
    address: "Lorong 1 Realty Park Hougang / Punggol / Sengkang (D19)",
    distance: "9 mins (720 m) from NE14/CR8 Hougang MRT",
    amount: "4501000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-parkwood-collection-25097214",
    about:
      '"About this propertyContact us today to make an inquiryBrand new listing•Only 2 years old •4510sqft landed•4 storey and 1 basement•5 huge bedrooms , of which 4 is ensuite •can park two car•open terrace in attic for private family event•comes with private lift Welcome to Parkwood CollectionTOP in 2022We are a 53 unit, leasehold, premium developmentLocated just 500m from hougang MRT Purple Line300 from future Hougang Cross island LineFor primary schools.Withint 1kmWe have Holy innocent Primary SchoolMontfort Junior SchoolXinhua Primary SchoolAndXinmin Primary SchoolWithin 1-2kmWe have famous schools such asRosyth SchoolPaya Lebar Methodist Girl SchoolCHIJ our Lady of the nativity Ask ken tay for a private tourI’ll see you 8***** Show more"',
    bed: 5,
    bath: 8,
    sqft: "4510",
    psf: null,
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "dfbd14af-b1ea-49a2-a429-a4b9f7555a90",
    title: "681B Jurong West Central 1",
    code: "DEPARTMENT-16",
    address: "681B Jurong West Central 1 Boon Lay / Jurong / Tuas (D22)",
    distance: "6 mins (480 m) from JS7 Bahar Junction MRT",
    amount: "638888",
    link: "https://www.propertyguru.com.sg/listing/hdb-for-sale-681b-jurong-west-central-1-25096916",
    about:
      '"About this propertyRare! Super convenient and spacious 5rm flat! Mins away to MRT!Welcome to Jurong West!- Located in the heart of Jurong West, this charming, 5Rm flat, 3 bedroom, 2 bathroom HDB offers a spacious 1237 sqft of living space.- Boasting a convenient location, this property is just a short walk away from Boon Lay MRT station (1.2km).- Nearby amenities include Boon Lay Secondary School (0.5km) and Dyslexia Association of Singapore (DAS) - Jurong Point Learning Centre (0.3km).- For your grocery needs, Sheng Siong Supermarket (0.6km) and Giant Hypermarket (0.8km) are easily accessible.- Enjoy shopping and dining at Jurong Point (0.3km) and The Centris Condominium (0.2km).- 3 months extension needed!- Don\'t miss out on this fantastic opportunity to own a home in this thriving neighborhood! Contact KT          9*****         now! Show more"',
    bed: 3,
    bath: 2,
    sqft: "1237",
    psf: "S$ 516",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
  {
    id: "e631e286-9769-45d9-9f5a-7cda82cdedb8",
    title: "Lentor Mansion",
    code: "DEPARTMENT-25",
    address: "52-64 Lentor Gardens Mandai / Upper Thomson (D26)",
    distance: "5 min (380 m) from TE5 Lentor MRT Station",
    amount: "Price On Ask",
    link: "https://www.propertyguru.com.sg/listing/project/for-sale-lentor-mansion-24991754?#",
    about:
      '"About this property: Luxury With Soul. Lentor Mansion is located in a distinctive all-private residential estate in Singapore, sprawling across the largest site in the neighborhood to date. Inspired by colonial black-and-white bungalows, the development promises tranquil mansion-style living amidst lush greenery. Residents will enjoy an iconic double-storey clubhouse that evokes a luxurious aesthetic rare in modern condominiums. Lentor Mansion is a mere 5-minute sheltered walk from Lentor MRT Station on the TEL line and a 96,000 sq ft shopping mall, and within 1km of CHIJ St. Nicholas Girls\' School and Anderson Primary School."',
    bed: 2,
    bath: 2,
    sqft: "527 - 1507",
    psf: null,
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "f5c21724-4fa9-4f88-aec3-ca8897d92e5d",
    title: "La Casa",
    code: "DEPARTMENT-24",
    address: "68 Woodlands Drive 16 Admiralty / Woodlands (D25)",
    distance: "11 mins (940 m) from TE3 Woodlands South MRT",
    amount: "1150000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-la-casa-25089106",
    about:
      '"About this propertySuper Motivated Seller! Pool View! Amenities! MRT! Functional Layout!* Premium pool view * 3 bed 3 bath unit* Well maintained * Functional layout* Motivated seller* Amenities - mins walk to Sheng Siong, Coffeeshop, Hawker Centre & Amenities* Plenty of Shopping - Vista Point / 888 Plaza / Causeway Point* MRT - Woodlands South & Admiralty* Schools - Preschool / Pri / Sec & even International Schools* Healthy 80 years balance lease*** Video AvaiLatha Kannan 9***** Show more"',
    bed: 3,
    bath: 3,
    sqft: "1141",
    psf: "S$ 1,008",
    createdAt: "2024-06-21T05:48:57.000Z",
    updatedAt: "2024-06-21T05:48:57.000Z",
    deletedAt: null,
  },
  {
    id: "fdb1c1f5-0fee-4267-89f9-a37d141d760b",
    title: "Duchess Manor",
    code: "DEPARTMENT-7",
    address: "20 Duchess Road Tanglin / Holland / Bukit Timah (D10)",
    distance: "11 mins (950 m) from DT8 Tan Kah Kee MRT",
    amount: "4250000",
    link: "https://www.propertyguru.com.sg/listing/for-sale-duchess-manor-24601025",
    about:
      '"About this propertyRare Penthouse for Sale in D10Four bedroom duplex penthouse for Sale.-1km to Nanyang Primary & Raffles Girls\' Primary.-5 minutes walk to Tan Kah Kee MRT station (DT8).-12min walk to Botanical Gardens.1st floor live-in space approx. 1700sqft 2nd floor outdoor space approx. 1600sqft -Keys on hand can view anytime.-Rarely available.Co-broke welcomeContact Simon Hum at          9*****         for viewing today. Show more"',
    bed: 4,
    bath: 3,
    sqft: "3218",
    psf: "S$ 1,321",
    createdAt: "2024-06-21T05:48:56.000Z",
    updatedAt: "2024-06-21T05:48:56.000Z",
    deletedAt: null,
  },
];

// Function to create PDF
function createPDF(data, filename) {
  const doc = new PDFDocument();
  const stream = fs.createWriteStream(filename);
  doc.pipe(stream);

  data.forEach((property) => {
    doc.text(`Code: ${property.code}`);
    doc.text(`Title: ${property.title}`);
    doc.text(`Address: ${property.address}`);
    doc.text(`Bedrooms: ${property.bed}`);
    doc.text(`Bathrooms: ${property.bath}`);
    doc.text(`Price: ${property.amount}`);
    doc.text(`${JSON.parse(property.about)}`);
    doc.moveDown(); // Add extra space between properties
  });

  doc.end();
  console.log(`PDF file "${filename}" created successfully.`);
}

// Generate PDF
createPDF(jsonData, "property_info.pdf");
